name: graduation_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  sensors_plus: ^4.0.2
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.6.0
  circle_nav_bar: ^2.0.1+1
  google_fonts: ^6.1.0
  date_picker_timeline: ^1.2.5
  gradient_icon: ^2.0.8
  pinput: ^3.0.1
  smooth_page_indicator: ^1.1.0
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  assets:
     - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

